language: php
php:
- 5.6
- 7.0
install:
- sudo pip install codecov
before_script:
- composer self-update
- composer install --no-interaction
after_success:
- bash <(curl -s https://codecov.io/bash)
script: 
- vendor/bin/php-cs-fixer fix app --verbose
- vendor/bin/phpunit --coverage-clover=coverage.xml
notifications:
  email: false